name: CRUtils
main: com.crazicrafter1.crutils.Main
version: 1.0.2 # last: 1.0.1
api-version: 1.13
author: crazicrafter1
softdepend: [PlaceholderAPI]

# 1.0.2 (10/17/2021)
# color codes


# 1.0.1 (10/15/2021)
# hotfixes


# 1.0.0 (10/12/2021)
# first version