name: CRUtils
main: com.crazicrafter1.crutils.Main
version: 1.0.5 # last: 1.0.4
api-version: 1.13
author: crazicrafter1
softdepend: [PlaceholderAPI]

# 1.0.5 (2/17/2022)
# restructured ItemBuilder to be more explicit, safe, and useful


# 1.0.4 (2/5/2022)
# 1.12.2 support


# 1.0.3 (1/14/2022)
# 1.18.1 support + fixes


# 1.0.2 (10/17/2021)
# color codes


# 1.0.1 (10/15/2021)
# hotfixes


# 1.0.0 (10/12/2021)
# first version