name: CRUtils
version: ${version}
main: com.crazicrafter1.crutils.Main
api-version: 1.19
softdepend: [ PlaceholderAPI ]
authors: [ crazicrafter1 ]
libraries:
  - org.apache.commons:commons-lang3:3.12.0